# Generated by Django 5.0.7 on 2024-08-07 17:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(datetime.date(2024, 8, 7)), django.core.validators.MaxValueValidator(datetime.date(2025, 8, 7))]),
        ),
    ]
